spring:
  profiles:
    active: prod
  application:
    name: catalog-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    username: user
    password: password
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  lifecycle:
    timeout-per-shutdown-phase: 15s

polar:
  greeting: "Polar greeting property value"

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: refresh
#        TODO: NOT AUTO REFRESHING FROM THE CONFIG SERVER SIDE (?)

server:
  port: 9001
  shutdown: graceful