spring:
  profiles:
    active: prod
  application:
    name: catalog-service
  config:
    import: "optional:configserver:http://localhost:8888"

polar:
  greeting: "Polar greeting property value"

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: refresh
#        TODO: NOT AUTO REFRESHING FROM THE CONFIG SERVER SIDE (?)